name: CD

on:
  create:
    tags:
      - v*

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python [3.7]
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}

    - name: Test variables
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}

    - name: Setup gcloud environment
      uses: GoogleCloudPlatform/github-actions@0.1.2
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    - run: gsutil cp gs://pyrotracker-credentials/back/firebase-service-account.json ./credentials/firebase-service-account.json

    - run: gcloud app deploy app.yml --quiet --project=pyrotracker --version=${{ env.RELEASE_VERSION }}
